### ISSUE TITLE
Any plans for a Android 5.x release?

### ISSUE THREAD

**Issue by gabeins** [wikichen/sketch-android-kit#4]
:grin:

**Comment by wikichen** [comment]
Google provides [an official Sketch template](http://www.google.com/design/spec/resources/sticker-sheets-icons.html#sticker-sheets-icons-components) for Material Design, or do you mean support for more display densities?

I did start on a 5.x template in the same vein but abandoned it after Google came out with their own. May revive it if you can convince me it's worth pursuing... :wink:

**Comment by gabeins** [comment]
I didn't see that official template from Google. I guess it's better to stick with their template then.

Thanks for this anyway!

**Comment by wikichen** [comment]
![sandlotbye](https://cloud.githubusercontent.com/assets/305375/7733474/0a6e2034-fee4-11e4-9e50-ab02d0a7a1dd.gif)
